"""empty message

Revision ID: 15bf2bb147a6
Revises: 50eb4a9e751c
Create Date: 2025-01-30 11:04:53.850136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15bf2bb147a6'
down_revision = '50eb4a9e751c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checkout', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_id', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checkout', schema=None) as batch_op:
        batch_op.drop_column('stripe_id')

    # ### end Alembic commands ###
