"""empty message

Revision ID: 50eb4a9e751c
Revises: c6c92f853621
Create Date: 2025-01-30 10:57:11.690839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50eb4a9e751c'
down_revision = 'c6c92f853621'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('country',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('country',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
