"""empty message

Revision ID: da629f48e6ae
Revises: f1e22329ceb3
Create Date: 2025-01-20 18:39:19.930253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da629f48e6ae'
down_revision = 'f1e22329ceb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('postalCode',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('city',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('city',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('postalCode',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
